version: '3.8'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile # Usar el Dockerfile personalizado
    container_name: php-apache8
    volumes:
      - ~/ProyectosPHP/Github/Github:/var/www/html # OJO AQUI PONER RUTA ~/ProyectosPHP
      #-~/ProyectosPHP:/var/www/html  C:\Apache24\htdocs
    ports:
      - "8081:80"
    depends_on:
      - mongo
      - mysql
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./dataMongoDB:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./dataMYSQL:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
